### ISSUE TITLE
Type is Used as a Parameter Name

### ISSUE THREAD

**Issue by desttinghim** [MasterQ32/zig-opengl#1]
`type` is used as a parameter name in a couple of functions, which prevents the bindings from compiling without modification. Presumably the code that generates the bindings could automatically rename these to something like `gltype` to make everything work out of the box.

**Comment by ikskuh** [comment]
Huh, i thought i had a commit already that fixed this. can you give me the commit you're on and where the error happened?

**Comment by desttinghim** [comment]
I downloaded the `gl_es_3v0.zig` file from the exports folder. Maybe those weren't updated?

**Comment by desttinghim** [comment]
Just cloned this repo and ran the program. Looks like this is still an issue :upside_down_face:  `texImage2D` (and many others) in the GLES 3.0 has this issue.

EDIT: Looks like it's been fixed by that latest commit. Thanks!
