### ISSUE TITLE
Clarify license for generated code

### ISSUE THREAD

**Issue by jcmoyer** [MasterQ32/zig-opengl#9]
Does the EUPL apply to generated bindings, or just the generator program? [glad](https://github.com/Dav1dde/glad) for example licenses the generator under The MIT License, but generated code as "any of Public Domain, WTFPL or CC0." I think it would be helpful to either make the same distinction for zig-opengl, or explicitly state that generated bindings are also covered under EUPL.

**Comment by ikskuh** [comment]
Good point. Imho the generated code is not licenced per se from `zig-opengl`, as the final author is the invocator of the tool, but i can see that this isn't a generally true statement.

**Comment by jcmoyer** [comment]
Thank you, I think 83d80ca107afdbc69b5f70198372cc4b90f5f359 addresses this issue so I'll close it.
